// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp-myocQDrWU-CoeSRC-Pxwpk-I9vk7bg',
    appId: '1:904454992035:web:cf7713d17fbf2e9e180f16',
    messagingSenderId: '904454992035',
    projectId: 'gwc-tamagotchi',
    authDomain: 'gwc-tamagotchi.firebaseapp.com',
    storageBucket: 'gwc-tamagotchi.firebasestorage.app',
    measurementId: 'G-49R3NFR391',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaQsAEtqaRKlfYOYNxtJ3L-f5hL6jNDd4',
    appId: '1:904454992035:android:10041292fc8b051b180f16',
    messagingSenderId: '904454992035',
    projectId: 'gwc-tamagotchi',
    storageBucket: 'gwc-tamagotchi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFc7oIpZAiSvep_3u76Q0ZJXCXr3aaUz4',
    appId: '1:904454992035:ios:5b50fffe16227b33180f16',
    messagingSenderId: '904454992035',
    projectId: 'gwc-tamagotchi',
    storageBucket: 'gwc-tamagotchi.firebasestorage.app',
    iosBundleId: 'com.example.project7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFc7oIpZAiSvep_3u76Q0ZJXCXr3aaUz4',
    appId: '1:904454992035:ios:5b50fffe16227b33180f16',
    messagingSenderId: '904454992035',
    projectId: 'gwc-tamagotchi',
    storageBucket: 'gwc-tamagotchi.firebasestorage.app',
    iosBundleId: 'com.example.project7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp-myocQDrWU-CoeSRC-Pxwpk-I9vk7bg',
    appId: '1:904454992035:web:5f55fd66343e7f7d180f16',
    messagingSenderId: '904454992035',
    projectId: 'gwc-tamagotchi',
    authDomain: 'gwc-tamagotchi.firebaseapp.com',
    storageBucket: 'gwc-tamagotchi.firebasestorage.app',
    measurementId: 'G-VSRV6VCZGS',
  );
}
